'use strict';
window.AdmissionView=(()=>{
  const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const sourceLink=(u,label='Источник ↗')=>{try{const url=new URL(u);return ['http:','https:'].includes(url.protocol)?`<a href="${escape(url.href)}" target="_blank" rel="noopener noreferrer">${escape(label)}</a>`:'';}catch{return '';}};
  let current,index=new Map(),limit=12,lastVisible=[];
  function init(data){if(current!==data){current=data;index=new Map((data.admission_sources||[]).map(r=>[r.domain,r]));document.querySelector('#visitor-category').onchange=()=>{limit=12;render(current,lastVisible);};document.querySelector('#reset').addEventListener('click',()=>{document.querySelector('#visitor-category').value='';limit=12;if(!document.querySelector('#admission').hidden)render(current,lastVisible);});}}
  const visitorPatterns={adult:/взросл|полный|обычный|стандартн/i,children:/дет|реб[её]н|школьн|учащ|до \d+ лет|от \d+ до \d+ лет/i,students:/студент|аспирант|isic/i,pensioners:/пенсион|пожил|старше \d+ лет/i,families:/многодет/i,disabled:/инвалид|ограниченными возможност|сопровождающ/i,veterans:/ветеран|военнослуж|геро[ийе]|сво|боевых действ/i};
  function visitorMatches(item,value){if(!value)return true;return visitorPatterns[value].test((item.category||'')+' '+(item.conditions||''))||/все посетители|всех посетителей|всем посетителям|все желающие|всех категорий/i.test(item.category||'');}
  function records(m,data){init(data);return (m.admission_domains||[]).map(d=>index.get(d)).filter(Boolean);}
  function matches(m,data,value){const rows=records(m,data);if(value==='prices')return rows.some(r=>r.tickets.length);if(value==='free-days')return rows.some(r=>r.free_rules.some(f=>['recurring_day','dated_event'].includes(f.rule_type)));if(value==='benefits')return rows.some(r=>r.free_rules.some(f=>['benefit','always'].includes(f.rule_type)));return true;}
  function badges(m,data){const rows=records(m,data);return `<div class="admission-badges">${rows.some(r=>r.tickets.length)?'<span>Есть стоимость</span>':''}${rows.some(r=>r.free_rules.some(f=>['recurring_day','dated_event'].includes(f.rule_type)))?'<span>Бесплатные дни / акции</span>':''}${rows.some(r=>r.free_rules.some(f=>['benefit','always'].includes(f.rule_type)))?'<span>Бесплатный вход для категорий</span>':''}</div>`;}
  function facts(row){
    const tickets=row.tickets||[],free=row.free_rules||[];
    const stamp=row.checked_at?new Date(row.checked_at).toLocaleDateString('ru-RU'):'';
    const ticketTable=tickets.length?`<div class="tariff-scroll"><table class="tariff-table"><thead><tr><th>Категория / билет</th><th>Стоимость</th><th>Условия и источник</th></tr></thead><tbody>${tickets.map(t=>`<tr><td><strong>${escape(t.category)}</strong>${t.scope?`<small>${escape(t.scope)}</small>`:''}</td><td class="tariff-price">${escape(t.price_text)}</td><td>${t.conditions?`<p>${escape(t.conditions)}</p>`:''}${sourceLink(t.source)}</td></tr>`).join('')}</tbody></table></div>`:'<p class="muted">Стоимость входного билета на проверенных страницах не найдена.</p>';
    const labels={always:'Бесплатный вход',benefit:'Бесплатно для категории',recurring_day:'Бесплатный день по расписанию',dated_event:'Акция с указанной датой'};
    const freeCards=free.length?free.map(f=>`<article class="free-rule"><span class="tag">${f.past_date?'Прошедшая акция':labels[f.rule_type]||'Бесплатное посещение'}</span><h4>${escape(f.when||'Условия бесплатного входа')}</h4><p><strong>Для кого:</strong> ${escape(f.category||'Категория в источнике не уточнена')}</p>${f.scope?`<p><strong>Посещение:</strong> ${escape(f.scope)}</p>`:''}${f.conditions?`<p><strong>Условия:</strong> ${escape(f.conditions)}</p>`:''}${sourceLink(f.source)}</article>`).join(''):'<p class="muted">Правила бесплатного входа на проверенных страницах не найдены.</p>';
    const incomplete=row.status==='partial'||row.input_truncated||row.rejected_count;
    return `<p class="admission-meta">Проверено ${escape(stamp)} · ${escape(row.domain)}${row.stale?' · показаны ранее сохранённые сведения':''}</p><p class="muted">Сведения общего сайта: тарифы могут относиться к разным зданиям и выставкам. Сверьте название площадки и условия своего билета.</p>${incomplete?'<p class="muted">Извлечена часть опубликованных сведений. Полный перечень тарифов и льгот смотрите в источнике.</p>':''}<h4 class="admission-subtitle">Стоимость по категориям</h4>${ticketTable}<h4 class="admission-subtitle">Когда и кому бесплатно</h4><div class="free-rules">${freeCards}</div><details class="admission-documents"><summary>Официальные страницы и прейскуранты</summary>${[...new Set(row.pages||[])].map(u=>sourceLink(u,u)).join('<br>')}</details>`;
  }
  function detail(m,data){const rows=records(m,data);if(!rows.length)return '<section class="admission-detail"><h3>Стоимость и бесплатные дни</h3><p class="muted">Проверенных сведений пока нет. Уточните стоимость и льготы на сайте музея.</p></section>';return `<section class="admission-detail"><h3>Стоимость и бесплатные дни</h3>${rows.map(r=>`<details ${rows.length===1?'open':''}><summary>${escape(r.name)} · ${r.tickets.length} тарифов · ${r.free_rules.length} правил</summary>${facts(r)}${!r.tickets.length&&!r.free_rules.length?(r.links||r.pages||[]).slice(0,3).map(u=>sourceLink(u,'Страница посещения ↗')).join(' · '):''}</details>`).join('')}</section>`;}
  function render(data,visible){init(data);lastVisible=visible;const visitor=document.querySelector('#visitor-category').value;const ids=new Set(visible.map(m=>m.id));const all=(data.admission_sources||[]).filter(r=>r.museum_ids.some(id=>ids.has(id))).map(r=>({...r,tickets:r.tickets.filter(t=>visitorMatches(t,visitor)),free_rules:r.free_rules.filter(f=>visitorMatches(f,visitor))})).filter(r=>r.tickets.length||r.free_rules.length);const filter=document.querySelector('#admission-filter').value;const rows=all.filter(r=>filter==='prices'?r.tickets.length:filter==='free-days'?r.free_rules.some(f=>['recurring_day','dated_event'].includes(f.rule_type)):filter==='benefits'?r.free_rules.some(f=>['always','benefit'].includes(f.rule_type)):true).sort((a,b)=>a.name.localeCompare(b.name,'ru'));document.querySelector('#admission-count').textContent=`Источников с данными: ${rows.length} · проверено сайтов: ${data.meta.admission_sources_checked||0} из ${data.meta.site_domains_total}. Не найденные сведения не означают бесплатный вход.`;document.querySelector('#admission-list').innerHTML=rows.slice(0,limit).map(r=>`<details class="admission-card"><summary><span><strong>${escape(r.name)}</strong><small>${escape(r.domain)}</small></span><span>${r.tickets.length} тарифов · ${r.free_rules.length} правил</span></summary><div class="admission-card-body">${facts(r)}</div></details>`).join('')||'<p class="empty">Сведений по этим условиям пока нет. Попробуйте другую категорию посетителя, тему или сбросьте фильтры.</p>';const more=document.querySelector('#more-admission');more.hidden=rows.length<=limit;more.onclick=()=>{limit+=12;render(data,visible);};}
  return {records,matches,badges,detail,render,resetPage:()=>{limit=12;}};
})();
