'use strict';
const $ = s => document.querySelector(s);
const esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safe = u => {try {const x=new URL(u);return ['http:','https:'].includes(x.protocol)?x.href:'';}catch{return '';}};
const link = (url,label) => safe(url) ? `<a href="${esc(safe(url))}" target="_blank" rel="noopener noreferrer">${esc(label)}</a>` : '';
const dayKey = d => `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const format = (d,opts={}) => new Date(d).toLocaleDateString('ru-RU',opts);
function foldIcs(line){const out=[];const encoder=new TextEncoder();let part='',bytes=0;for(const char of line){const size=encoder.encode(char).length;if(bytes+size>75){out.push(part);part=' ';bytes=1;}part+=char;bytes+=size;}out.push(part);return out;}
let data, visible=[], tab='catalog', museumLimit=24, map, layer, period='week', anchor=new Date(), selectedDay='';
function range(){let start=new Date(anchor.getFullYear(),anchor.getMonth(),anchor.getDate()),end=new Date(start);if(period==='week'){start.setDate(start.getDate()-(start.getDay()+6)%7);end=new Date(start);end.setDate(end.getDate()+7);}else if(period==='month'){start.setDate(1);end=new Date(start.getFullYear(),start.getMonth()+1,1);}else{start=new Date(start.getFullYear(),0,1);end=new Date(start.getFullYear()+1,0,1);}return [start,end];}
function filteredEvents(){const q=$('#search').value.toLocaleLowerCase('ru').trim(),cat=$('#category').value,theme=$('#theme').value,tg=$('#tg-only').checked;const allowed=new Set(data.museums.filter(m=>(!cat||m.category===cat)&&(!theme||m.themes.includes(theme))&&(!tg||m.telegram.length)&&window.AdmissionView.matches(m,data,$('#admission-filter').value)).map(m=>m.id));const visibleIds=new Set(visible.map(m=>m.id));const kind=$('#event-kind').value,source=$('#calendar-source').value,mode=$('#calendar-mode').value;return data.events.filter(e=>e.museum_ids.some(id=>allowed.has(id))&&(!q||e.title.toLocaleLowerCase('ru').includes(q)||e.museum_ids.some(id=>visibleIds.has(id)))&&(!kind||e.kind===kind)&&(!source||e.source_site===source)&&(mode==='all'||(mode==='periods')===(e.schedule_type==='period'))&&!String(e.status).includes('EventCancelled'));}
function occurs(e,date){const key=dayKey(date);if(e.occurrence_dates)return e.occurrence_dates.includes(key);const start=e.start.slice(0,10),end=(e.end||e.start).slice(0,10);return start<=key&&key<=end;}
function currentEvents(){const [a,b]=range();return filteredEvents().filter(e=>(e.end||e.start).slice(0,10)>=dayKey(a)&&e.start.slice(0,10)<dayKey(b)&&(!e.occurrence_dates||e.occurrence_dates.some(d=>d>=dayKey(a)&&d<dayKey(b))));}
function updateFilters(){const q=$('#search').value.toLocaleLowerCase('ru').trim(),cat=$('#category').value,theme=$('#theme').value,tg=$('#tg-only').checked;visible=data.museums.filter(m=>(!cat||m.category===cat)&&(!theme||m.themes.includes(theme))&&(!tg||m.telegram.length)&&window.AdmissionView.matches(m,data,$('#admission-filter').value)&&(!q||[m.name,m.address,m.category,...m.themes].join(' ').toLocaleLowerCase('ru').includes(q)));const sorting=$('#sort').value;visible.sort((a,b)=>sorting==='name-desc'?b.name.localeCompare(a.name,'ru'):sorting==='theme'?a.themes[0].localeCompare(b.themes[0],'ru')||a.name.localeCompare(b.name,'ru'):sorting==='format'?a.category.localeCompare(b.category,'ru')||a.name.localeCompare(b.name,'ru'):a.name.localeCompare(b.name,'ru'));museumLimit=24;window.TelegramFeed.resetPage();window.AdmissionView.resetPage();render();}
function renderThemeChips(){const active=$('#theme').value;$('#theme-chips').innerHTML=data.themes.map(t=>{const count=data.museums.filter(m=>m.themes.includes(t)).length;return count?`<button data-theme="${esc(t)}" class="${active===t?'active':''}" aria-pressed="${active===t}">${esc(t)} <span>${count}</span></button>`:'';}).join('');}

function render(){if(!data)return;renderThemeChips();$('#status').textContent=`Каталог кандидатов · обновлено ${format(data.meta.built_at)} · расписания могут быть неполными`;if(tab==='catalog')renderMuseums();if(tab==='map')renderMap();if(tab==='events')renderEvents();if(tab==='telegram')renderPosts();if(tab==='admission')window.AdmissionView.render(data,visible);}
function renderMuseums(){$('#catalog-count').textContent=`Найдено: ${visible.length}. Данные справочников требуют проверки.`;$('#museum-list').innerHTML=visible.slice(0,museumLimit).map(m=>`<article class="museum-card"><span class="tag">${esc(m.category)}</span><h3>${esc(m.name)}</h3><span class="theme-label">${esc(m.themes.join(' · '))}</span><p>${esc(m.address||'Адрес не указан')}</p>${window.AdmissionView.badges(m,data)}<div class="card-footer"><button data-museum="${esc(m.id)}">Открыть музей ↗</button><span>${m.telegram.length?'Telegram · ':''}${m.sites.length?'Есть сайт':'Без сайта'}</span></div></article>`).join('')||'<p class="empty">По этим условиям музеев не найдено. Попробуйте другой запрос.</p>';$('#more').hidden=visible.length<=museumLimit;}
function showMuseum(id){const m=data.museums.find(x=>x.id===id);if(!m)return;$('#museum-detail').innerHTML=`<p class="tag">${esc(m.category)}</p><h2>${esc(m.name)}</h2><p>${esc(m.address)}</p><p class="theme-label">${esc(m.themes.join(' · '))}</p><p class="muted">${esc(m.theme_source)}</p><p class="muted">${esc(m.verification)}${m.checked_at?' · сайт проверен '+format(m.checked_at):''}</p><div class="detail-links">${m.sites.map(u=>link(u,'Сайт ↗')).join('')}${m.telegram.map(u=>link(u,'Telegram ↗')).join('')}</div><div class="detail-contacts"><p><b>Телефоны:</b> ${esc(m.phones.join(', ')||'Не найдены')}</p><p><b>Email:</b> ${esc(m.emails.join(', ')||'Не найдены')}</p><p><b>Время работы из справочника:</b> ${esc(m.hours||'Не указано')}</p></div>${window.AdmissionView.detail(m,data)}<h3>Афиша и новости</h3><div class="detail-links">${m.agenda.map(u=>link(u,'Афиша ↗')).join('')}${m.news.map(u=>link(u,'Новости ↗')).join('')||(!m.agenda.length?'<p class="muted">Разделы пока не найдены.</p>':'')}</div><p class="muted">Контакты общего сайта могут относиться к организации, а не к этому филиалу.</p><p class="muted">Источники: ${esc([...new Set(m.sources.map(s=>s.engine))].join(', '))}. ${m.website_errors.length?'Часть страниц недоступна.':''}</p>${m.lat!==null?`<button data-locate="${m.id}">Показать на карте</button>`:''}`;$('#museum-dialog').showModal();}
function setTab(value){tab=value;document.querySelectorAll('.panel').forEach(p=>p.hidden=p.id!==tab);document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));history.replaceState(null,'','#'+tab);render();}
function renderMap(){const points=visible.filter(m=>Number.isFinite(m.lat)&&Number.isFinite(m.lon));$('#map-count').textContent=`${points.length} точек · без координат: ${visible.length-points.length}`;if(!window.L){$('#map-canvas').innerHTML='<p class="empty">Библиотека карты недоступна. Каталог можно просмотреть в разделе «Музеи».</p>';return;}if(!map){map=L.map('map-canvas',{preferCanvas:true}).setView([55.753,37.62],10);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>'}).addTo(map);layer=L.layerGroup().addTo(map);}layer.clearLayers();for(const m of points){const box=document.createElement('div');const title=document.createElement('strong');title.textContent=m.name;box.append(title);const address=document.createElement('p');address.textContent=m.address;box.append(address);const btn=document.createElement('button');btn.textContent='Открыть музей';btn.addEventListener('click',()=>showMuseum(m.id));box.append(btn);L.circleMarker([m.lat,m.lon],{radius:5,color:'#355841',weight:1,fillColor:'#355841',fillOpacity:.7}).bindPopup(box).addTo(layer);}requestAnimationFrame(()=>map.invalidateSize());}
function renderEvents(){const [start,end]=range(),events=currentEvents();$('#period-label').textContent=period==='year'?String(start.getFullYear()):period==='month'?format(start,{month:'long',year:'numeric'}):`${format(start)} — ${format(new Date(end.getTime()-86400000))}`;document.querySelectorAll('[data-period]').forEach(b=>b.classList.toggle('active',b.dataset.period===period));if(period==='year'){$('#calendar').innerHTML=`<div class="year-grid">${Array.from({length:12},(_,i)=>{const d=new Date(start.getFullYear(),i,1);const count=events.filter(e=>(e.end||e.start).slice(0,10)>=dayKey(d)&&e.start.slice(0,10)<dayKey(new Date(d.getFullYear(),i+1,1))).length;return `<button data-month="${i}"><strong>${esc(format(d,{month:'long'}))}</strong><span>${count} событий</span></button>`;}).join('')}</div>`;}else{const gridStart=new Date(start);if(period==='month')gridStart.setDate(1-(gridStart.getDay()+6)%7);const length=period==='week'?7:Math.ceil(((start.getDay()+6)%7+new Date(start.getFullYear(),start.getMonth()+1,0).getDate())/7)*7;$('#calendar').innerHTML=`<div class="month-grid">${['Пн','Вт','Ср','Чт','Пт','Сб','Вс'].map(x=>`<div class="weekday">${x}</div>`).join('')}${Array.from({length},(_,i)=>{const d=new Date(gridStart);d.setDate(d.getDate()+i);const count=events.filter(e=>occurs(e,d)).length;const key=dayKey(d);return `<button class="day ${period==='month'&&d.getMonth()!==start.getMonth()?'disabled':''} ${key===dayKey(new Date())?'today':''} ${selectedDay===key?'selected':''}" data-day="${key}"><b>${d.getDate()}</b>${count?`<small>${count} событий</small>`:''}</button>`;}).join('')}</div>`;}
events.sort((a,b)=>(a.schedule_type==='period')-(b.schedule_type==='period')||a.start.localeCompare(b.start));const listing=selectedDay?events.filter(e=>occurs(e,new Date(selectedDay+'T12:00:00'))):events;$('#event-list').innerHTML=(selectedDay?`<p class="muted">Выбран день: ${format(selectedDay+'T12:00:00')} · <button id="all-days" class="quiet">Весь период</button></p>`:'')+(listing.map(e=>`<article class="event-row"><time>${esc(format(e.start))}${e.date_precision==='time'?'<br>'+esc(new Date(e.start).toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit',timeZone:'Europe/Moscow'}))+' мск':''}</time><div><span class="tag">${esc(e.kind)} · ${esc(e.source_site||'')}</span><h3>${esc(e.title)}</h3><p>${esc(e.venue_note)}</p><p>${e.schedule_type==='period'?'Период программы: '+esc(format(e.start))+' — '+esc(format(e.end))+'. Сеансы уточняйте в источнике.':e.occurrence_dates?'Дни проведения перечислены в календаре музея; время уточняйте в источнике.':''}</p>${e.requires_review?'<p>Даты извлечены общим парсером; проверьте программу в источнике.</p>':''}${e.year_inferred?'<p>Год принят по текущей афише — проверьте перед визитом.</p>':''}${e.stale?'<p>Последняя проверка не удалась; показаны ранее сохранённые даты.</p>':''}</div>${link(e.url,'Программа и билеты ↗')}</article>`).join('')||'<p class="empty">На этот период подтверждённых дат пока нет. Посмотрите афиши ниже: часть сайтов не публикует расписание в доступной разметке.</p>');const agendas=new Map();for(const m of visible){for(const u of m.agenda)if(!agendas.has(u))agendas.set(u,m.name);}$('#agenda-list').innerHTML=[...agendas].slice(0,48).map(([u,name])=>`<div class="agenda-link">${link(u,name+' ↗')}</div>`).join('')||'<p class="empty">Афиши ещё не собраны для выбранных музеев.</p>';}
function renderPosts(){window.TelegramFeed.render(data,visible);}

function exportIcs(){const events=currentEvents();const escapeIcs=s=>String(s).replace(/\\/g,'\\\\').replace(/\n/g,'\\n').replace(/;/g,'\\;').replace(/,/g,'\\,');const date=s=>s.slice(0,10).replace(/-/g,'');const stamp=s=>new Date(s).toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'');const rows=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Museum Route//RU','CALSCALE:GREGORIAN'];const [from,to]=range();for(const original of events){const e={...original};if(e.occurrence_dates){e.occurrence_dates=e.occurrence_dates.filter(d=>d>=dayKey(from)&&d<dayKey(to));e.start=e.occurrence_dates[0];}rows.push('BEGIN:VEVENT',`UID:${e.id}@museum-route.local`,`DTSTAMP:${stamp(data.meta.built_at)}`);if(e.date_precision==='day'){rows.push(`DTSTART;VALUE=DATE:${date(e.start)}`);const end=new Date((e.end||e.start).slice(0,10)+'T12:00:00');end.setDate(end.getDate()+1);if(e.occurrence_dates){const next=new Date(e.start.slice(0,10)+'T12:00:00');next.setDate(next.getDate()+1);rows.push(`DTEND;VALUE=DATE:${dayKey(next).replace(/-/g,'')}`);const extra=e.occurrence_dates.filter(d=>d!==e.start.slice(0,10));if(extra.length)rows.push('RDATE;VALUE=DATE:'+extra.map(d=>d.replace(/-/g,'')).join(','));}else rows.push(`DTEND;VALUE=DATE:${dayKey(end).replace(/-/g,'')}`);}else{const start=/[Zz]|[+-]\d\d:\d\d$/.test(e.start)?e.start:e.start+'+03:00';rows.push(`DTSTART:${stamp(start)}`);if(e.end){const end=/[Zz]|[+-]\d\d:\d\d$/.test(e.end)?e.end:e.end+'+03:00';rows.push(`DTEND:${stamp(end)}`);}}rows.push(`SUMMARY:${escapeIcs(e.title)}`,`URL:${escapeIcs(e.url)}`,`DESCRIPTION:${escapeIcs(e.venue_note)}`,'END:VEVENT');}rows.push('END:VCALENDAR');const blob=new Blob([rows.flatMap(foldIcs).join('\r\n')+'\r\n'],{type:'text/calendar;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='museum-events.ics';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.theme){$('#theme').value=$('#theme').value===b.dataset.theme?'':b.dataset.theme;updateFilters();}if(b.dataset.tab)setTab(b.dataset.tab);if(b.dataset.museum)showMuseum(b.dataset.museum);if(b.dataset.locate){$('#museum-dialog').close();setTab('map');const m=data.museums.find(x=>x.id===b.dataset.locate);map?.setView([m.lat,m.lon],16);}if(b.dataset.period){period=b.dataset.period;selectedDay='';renderEvents();}if(b.dataset.day){selectedDay=b.dataset.day;renderEvents();}if(b.dataset.month!==undefined){anchor=new Date(anchor.getFullYear(),Number(b.dataset.month),1);period='month';selectedDay='';renderEvents();}if(b.id==='all-days'){selectedDay='';renderEvents();}});
$('#search').addEventListener('input',()=>data&&updateFilters());['category','theme','sort','tg-only','admission-filter'].forEach(id=>$('#'+id).addEventListener('change',()=>data&&updateFilters()));$('#reset').onclick=()=>{$('#search').value='';$('#category').value='';$('#theme').value='';$('#sort').value='name';$('#tg-only').checked=false;$('#admission-filter').value='';$('#calendar-source').value='';$('#calendar-mode').value='all';$('#event-kind').value='';selectedDay='';updateFilters();};$('#more').onclick=()=>{museumLimit+=24;renderMuseums();};$('#event-kind').onchange=renderEvents;$('#calendar-source').onchange=renderEvents;$('#calendar-mode').onchange=renderEvents;$('#close-dialog').onclick=()=>$('#museum-dialog').close();$('#museum-dialog').addEventListener('click',e=>{if(e.target===$('#museum-dialog'))$('#museum-dialog').close();});$('#today').onclick=()=>{anchor=new Date();selectedDay='';renderEvents();};['prev','next'].forEach(id=>$('#'+id).onclick=()=>{const direction=id==='prev'?-1:1;if(period==='week')anchor.setDate(anchor.getDate()+7*direction);else if(period==='month')anchor=new Date(anchor.getFullYear(),anchor.getMonth()+direction,1);else anchor=new Date(anchor.getFullYear()+direction,0,1);selectedDay='';renderEvents();});$('#export-ics').onclick=exportIcs;
fetch('data/catalog.json').then(r=>{if(!r.ok)throw new Error('HTTP '+r.status);return r.json();}).then(d=>{data=d;visible=d.museums;initEventSources();$('#theme').innerHTML='<option value="">Все темы</option>'+d.themes.map(t=>`<option>${esc(t)}</option>`).join('');$('#stats').innerHTML=[[d.meta.museums,'записей в каталоге'],[d.meta.with_coordinates,'точек на карте'],[d.meta.channels,'Telegram-ссылок'],[d.meta.events,'найденных событий']].map(([n,t])=>`<div class="stat"><strong>${n}</strong><span>${t}</span></div>`).join('');$('#channel').innerHTML='<option value="">Все каналы</option>'+d.channels.map(c=>`<option value="${esc(c.url)}">@${esc(c.url.split('/').pop())}</option>`).join('');$('#source-report').innerHTML=`<div class="source-metrics"><div><strong>${d.meta.site_domains_checked} / ${d.meta.site_domains_total}</strong><span>доменов проверено · доступны ${d.meta.site_domains_available}</span></div><div><strong>${d.meta.channels_available} / ${d.meta.channels}</strong><span>каналов с доступной лентой</span></div><div><strong>${d.meta.posts}</strong><span>сохранённых публикаций</span></div></div><p class="muted">Сборка: ${format(d.meta.built_at)}. Исходных строк: ${d.meta.raw_rows}; исключено по географии и рубрике: ${d.meta.excluded_rows}.</p>`;setTab(['catalog','map','events','admission','telegram','sources'].includes(location.hash.slice(1))?location.hash.slice(1):'catalog');}).catch(e=>{$('#status').textContent='Не удалось загрузить каталог: '+e.message+'. Запустите python serve.py и откройте локальный адрес.';});

function initEventSources(){
 const sources=(data.event_sources||[]).filter(r=>r.events&&r.calendar_enabled!==false).sort((a,b)=>a.name.localeCompare(b.name,'ru'));
 $('#calendar-source').innerHTML='<option value="">Все источники</option>'+sources.map(r=>`<option value="${esc(r.domain)}">${esc(r.name)} · ${r.events}</option>`).join('');
 $('#event-kind').innerHTML='<option value="">Все события</option>'+[...new Set(data.events.map(e=>e.kind))].sort((a,b)=>a.localeCompare(b,'ru')).map(k=>`<option>${esc(k)}</option>`).join('');
 $('#calendar-coverage').textContent=`Проверено сайтов: ${data.meta.event_sources_checked||0}; в календарь включено ${sources.length} источников. Обновлено ${format(data.meta.built_at)}. Пустые дни могут означать неполное покрытие.`;
 const statuses={ok:'Даты найдены',partial:'Частичный сбор',no_dates:'Даты не найдены',needs_adapter:'Нужен адаптер',unavailable:'Сайт недоступен',not_checked:'Не проверен'};
 const all=[...(data.event_sources||[])].sort((a,b)=>b.events-a.events||a.name.localeCompare(b.name,'ru'));
 $('#event-source-table').innerHTML='<table><thead><tr><th>Музей / сайт</th><th>Сборщик</th><th>Результат</th><th>Программ / сеансов</th><th>Проверен</th></tr></thead><tbody>'+all.map(r=>`<tr><td>${link(r.seeds[0],r.name)}<small>${esc(r.domain)}</small></td><td>${r.adapter==='generic'?'Общий поиск':'Индивидуальный'}</td><td>${esc(r.calendar_enabled===false?'Не включён в календарь':statuses[r.status]||r.status)}${r.errors?' · ошибки: '+r.errors:''}${r.review_note?'<small>'+esc(r.review_note)+'</small>':''}</td><td>${r.events}</td><td>${r.checked_at?format(r.checked_at):'—'}</td></tr>`).join('')+'</tbody></table>';
}
